language: python

python:
  - 2.7
  - 3.4

before_install:
  # Python
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  
  # system libs
  - sudo apt-get install libraw-dev liblensfun-dev ffmpeg libnetcdf-dev libhdf5-serial-dev
  
  # CDF
  - wget http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf35_0_2/linux/cdf35_0-dist-cdf.tar.gz
  - tar -zxvf cdf35_0-dist-cdf.tar.gz
  - cd cdf35_0-dist
  - make OS=linux ENV=gnu all
  - sudo make INSTALLDIR=/usr/local/cdf install
  - cd ..

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  # we use conda to prevent compiling big packages
  - conda install --yes numpy scipy astropy scikit-image pillow matplotlib basemap pip
  - pip install -r dev-requirements.txt
  - python setup.py sdist
  # manually install extra dependencies, this is a
  # work-around until https://github.com/pypa/pip/issues/1236 is fixed
  - pip install netCDF4
  - pip install git+http://git.code.sf.net/p/spacepy/code@412003
  - pip install dist/*.tar.gz
  
script:
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../auromat/test
  - cd ..
  