language: objective-c

env:
  matrix:
    - VERSION=2
    - VERSION=3

install:
  - cd terryfy && git fetch && git checkout master && cd ..
  - source terryfy/travis_tools.sh
  - travis_retry get_python_environment homebrew $VERSION venv

  # CDF
  - wget http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf35_0_2/linux/cdf35_0-dist-cdf.tar.gz
  - tar -zxvf cdf35_0-dist-cdf.tar.gz
  - cd cdf35_0-dist
  - make OS=macosx ENV=gnu all
  - sudo make INSTALLDIR=/usr/local/cdf install
  - cd ..

  # spacepy
  - pip install numpy python-dateutil
  - git clone --depth 1 http://git.code.sf.net/p/spacepy/code spacepy
  - cd spacepy && python setup.py install && cd ..
  
  # some other native software/libraries
  - brew install exiftool ffmpeg
  
  - brew tap homebrew/science
  - brew install netcdf hdf5
  
  # and finally install auromat itself
  - pip install auromat[cdf,netcdf]
  

script:
  - pip install nose
  - nosetests --verbosity=3 --nocapture -a '!slow' auromat.test
