language: python

python:
  - "2.7"
  - "3.4"

install:
  - sudo apt-get install libatlas-dev libatlas-base-dev liblapack-dev
  - sudo apt-get install libraw-dev liblensfun-dev
  # scikit-image 0.10.1 needs six at setup but doesn't install it
  - pip install six
  - python setup.py sdist
  - pip install dist/*.tar.gz
  
script:
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests ../auromat/test
  - cd ..