language: objective-c

env:
#  global:
    #- LATEST_TAG=1
  matrix:
    - VERSION=2
    - VERSION=3

# 'cat' is used to emulate a non-tty shell, see https://github.com/travis-ci/travis-ci/issues/3034

install:
  - cd terryfy && git fetch && git checkout master && cd ..
  - source terryfy/travis_tools.sh
  - travis_retry get_python_environment homebrew $VERSION venv
  - echo $PATH
  - python --version
  - if [ -n "$LATEST_TAG" ]; then 
      checkout_closest_tag auromat ;
    else
      cd auromat ;
      git fetch ;
      git checkout -f master ;
      git log -n 1 ;
      cd .. ;
    fi

  # CDF
  - wget http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/cdf35_0_2/linux/cdf35_0-dist-cdf.tar.gz
  - tar -zxvf cdf35_0-dist-cdf.tar.gz
  - cd cdf35_0-dist
  - make OS=macosx ENV=gnu all
  - sudo make INSTALLDIR=/Applications/cdf install
  - cd ..

  # spacepy
  - pip install numpy python-dateutil | cat
  - pip install git+http://git.code.sf.net/p/spacepy/code | cat
  
  # some other native software/libraries
  - brew install exiftool ffmpeg | cat
  
  - brew tap homebrew/science
  - brew install netcdf hdf5 | cat
  
  # and finally install auromat itself
  - cd auromat
  - python setup.py sdist
  - pip install dist/*.tar.gz | cat
  
  - cd ..

script:
  - pip install nose | cat
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture -a '!slow' ../auromat/auromat/test
  - cd ..
