language: python

python:
  - 2.7
  - 3.4

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - sudo apt-get install libraw-dev liblensfun-dev

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  # we use conda to prevent compiling big packages
  - conda install --yes numpy scipy astropy scikit-image pillow matplotlib pip
  - pip install -r dev-requirements.txt
  - python setup.py sdist
  - pip install dist/*.tar.gz
  
script:
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../auromat/test
  - cd ..